language: java
os: osx
env:
  global:
  - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk: openjdk10
script:
- ls
- ls LavalinkServer
- ls LavalinkServer/build
- ls LavalinkServer/build/libs

deploy:
  provider: releases
  api_key:
    secure: MfmDH3s9vrlZ+tOo2Npyu0BqpLCTB8bJ6tUKx1yQiBK7F5jjiQwxvppAjHLaXL45N5tLeJjQC2qA54xWBQrP1Q918CwlIFnxA6FivG/bFOav01qpL0eznazp5qeypndio2gOMFin1amzEIZxEnGFqEsFzCjOZnmEexxMOO5LUTRyXNAP7BRRTyMm3QC/eSbuSEzKvBkD52N7TyNimJ76GuSUuq9Ce9rj2HmNEf88VclPh4CeHNhwegdUw30tj5pvRd1yRBFI9/XN5+YzJfEyns+4cEg3lygllxdWHL4yyitA8jwbsyzR6HEgMxoRsn5i2bhjPLqC7OrDHojlyZfmukh5Fs6bYYaTIO2UOWKGIzWNzLuEzfCintm6oYRwtU9TuJaOXNyH1vqOeGg8kT6AozZlx5Gk0PLHFIErfLcdNpcbc0Rx5kidRlhkYAkr4x4Jz2p6qMm+IgX9dv2MLtEF9L1IqH9lQwUIMMgNbEvPkvjyddKC6taOQTJ2+mERCzqblVlagu01sWAQcIpyHjPpnojqUDfQvg4LrEN+D4EYz/S2mC5YZdVo2rDpQBPnwGNbBn4/B2r26pBjAe/MJiyYG4R45L3rhQsg6V32PnMsV4bWJFjHMJZ2gq6cSuD+OLngz3ZLFPlInFHbZcti5/1ecJfmG4eYdPJ2d/F1fI+BY4k=
  file: ./LavalinkServer/build/libs/Lavalink.jar
  on:
    repo: Tobotimus/Lavalink
    tags: true
